### ISSUE TITLE
Re-name environments and controllers. Current naming is too confusing and unorganised

### ISSUE THREAD

**Issue by JinraeKim** [JinraeKim/FSimZoo.jl#3]
How about changing predefined stuffs' names, e.g., `LinearSystemEnv` -> `LinearSystem`, `MulticopterEnv` -> `Multicopter`?

**Comment by JinraeKim** [comment]
Reason: suffix `Env` is redundant and does not coincide with other stuffs, e.g., `PseudoInverseAllocator`.

**Comment by hnlee77** [comment]
Sounds like good.
